<?php
/**
 * Template Name: About
 * Description: Displays the about page.
 *
 * @package BadBoyBike
 */

get_header();
?>

<section class="about" id="about">
    <div class="container">
        <div class="about__header">
            <h1 class="section-title"><?php the_title(); ?></h1>
        </div>

        <div class="about__grid" id="aboutGrid">
            <!-- About content will be generated by JavaScript -->
        </div>
    </div>
</section>

<?php
get_footer();


