    <!-- FOOTER -->
    <footer class="footer">
        <div class="container">
            <div class="footer__container">
                <div class="footer__section">
                    <h3 class="footer__section-title"><?php bloginfo('name'); ?></h3>
                    <p class="footer__text">
                        <?php bloginfo('description'); ?>
                    </p>
                </div>
                
                <div class="footer__section">
                    <h3 class="footer__section-title">Quick Links</h3>
                    <?php
                    wp_nav_menu(array(
                        'theme_location' => 'footer',
                        'menu_class' => '',
                        'container' => 'nav',
                        'fallback_cb' => false,
                    ));
                    ?>
                </div>
                
                <div class="footer__section">
                    <h3 class="footer__section-title">Follow Us</h3>
                    <div class="social-links">
                        <?php
                        $facebook = get_theme_mod('badboybike_facebook');
                        $instagram = get_theme_mod('badboybike_instagram');
                        $youtube = get_theme_mod('badboybike_youtube');
                        
                        if ($facebook) echo '<a href="' . esc_url($facebook) . '" class="social-link" aria-label="Facebook" target="_blank">FB</a>';
                        if ($instagram) echo '<a href="' . esc_url($instagram) . '" class="social-link" aria-label="Instagram" target="_blank">IG</a>';
                        if ($youtube) echo '<a href="' . esc_url($youtube) . '" class="social-link" aria-label="YouTube" target="_blank">YT</a>';
                        ?>
                    </div>
                </div>
            </div>
            
            <div class="footer__bottom">
                <p>&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?>. All rights reserved.</p>
            </div>
        </div>
    </footer>

    <!-- MODAL -->
    <div class="modal" id="bikeModal">
        <button class="modal__close" id="modalClose" aria-label="Close modal">&times;</button>
        <div class="modal__container">
            <div class="modal__content">
                <div class="modal__gallery">
                    <div class="modal__main-image">
                        <img src="" alt="" id="modalMainImage">
                    </div>
                    <div class="modal__thumbnails" id="modalThumbnails">
                        <!-- Thumbnails will be generated by JavaScript -->
                    </div>
                </div>
                
                <div class="modal__details">
                    <div>
                        <h2 class="modal__title" id="modalTitle"></h2>
                        <p class="modal__model" id="modalModel"></p>
                    </div>
                    
                    <div>
                        <h3 class="footer__section-title">Description</h3>
                        <p class="modal__description" id="modalDescription"></p>
                    </div>
                    
                    <div>
                        <h3 class="footer__section-title">Specifications</h3>
                        <div class="modal__specs-list" id="modalSpecs">
                            <!-- Specs will be generated by JavaScript -->
                        </div>
                    </div>
                    
                    <div>
                        <h3 class="footer__section-title">Modifications</h3>
                        <div class="modal__modifications" id="modalModifications">
                            <!-- Modifications will be generated by JavaScript -->
                        </div>
                    </div>
                    
                    <button class="btn btn--primary" onclick="window.location.href='#contact'">INQUIRE ABOUT THIS BUILD</button>
                </div>
            </div>
        </div>
    </div>

    <?php wp_footer(); ?>
</body>
</html>


