<?php
/**
 * The main template file
 *
 * @package BadBoyBike
 */

get_header();
?>

<!-- HERO SECTION -->
<section class="hero" id="home">
    <div class="hero__background">
        <?php
        $hero_image = get_theme_mod('badboybike_hero_image');
        if ($hero_image) {
            echo '<img src="' . esc_url($hero_image) . '" alt="Custom Harley-Davidson motorcycle">';
        } else {
            echo '<img src="' . get_template_directory_uri() . '/images/hero-bike.jpg" alt="Custom Harley-Davidson motorcycle">';
        }
        ?>
    </div>
    
    <div class="container">
        <div class="hero__content">
            <h1 class="hero__title">
                <?php echo get_theme_mod('badboybike_hero_title', 'HARLEY-DAVIDSON<br>CUSTOM SHOP'); ?>
            </h1>
            <p class="hero__subtitle">
                <?php echo get_theme_mod('badboybike_hero_subtitle', 'UNIQUE CUSTOM BIKES BUILT TO PERFECTION'); ?>
            </p>
            <a href="#customs" class="btn btn--primary">VIEW CUSTOMS</a>
        </div>
    </div>
</section>

<!-- FEATURES SECTION -->
<section class="features">
    <div class="container">
        <div class="features__grid">
            <!-- Feature 1: Custom Motorcycles -->
            <article class="feature-card">
                <div class="feature-card__background">
                    <img src="<?php echo get_template_directory_uri(); ?>/images/feature-custom.jpg" alt="Custom Motorcycles">
                </div>
                <div class="feature-card__overlay">
                    <h2 class="feature-card__title">CUSTOM<br>MOTORCYCLES</h2>
                </div>
            </article>
            
            <!-- Feature 2: Parts & Accessories -->
            <article class="feature-card">
                <div class="feature-card__background">
                    <img src="<?php echo get_template_directory_uri(); ?>/images/feature-parts.jpg" alt="Parts and Accessories">
                </div>
                <div class="feature-card__overlay">
                    <h2 class="feature-card__title">PARTS &<br>ACCESSORIES</h2>
                </div>
            </article>
            
            <!-- Feature 3: About Us -->
            <article class="feature-card">
                <div class="feature-card__background">
                    <img src="<?php echo get_template_directory_uri(); ?>/images/feature-about.jpg" alt="About Us">
                </div>
                <div class="feature-card__overlay">
                    <h2 class="feature-card__title">ABOUT<br>US</h2>
                </div>
            </article>
        </div>
    </div>
</section>

<!-- ABOUT SECTION -->
<section class="about" id="about">
    <div class="container about__container">
        <h2 class="section-title"><?php echo get_theme_mod('badboybike_about_title', 'About Bad Boy Bike'); ?></h2>
        <?php
        $about_content = get_theme_mod('badboybike_about_content');
        if ($about_content) {
            echo wpautop($about_content);
        } else {
            ?>
            <p class="about__text">
                We are a premium Harley-Davidson custom shop dedicated to creating unique, one-of-a-kind motorcycles 
                that reflect your personal style and vision. With years of experience and a passion for perfection, 
                we transform standard bikes into extraordinary machines.
            </p>
            <p class="about__text">
                Every custom build is a collaboration between our expert craftsmen and you. From concept to completion, 
                we ensure every detail is meticulously crafted to exceed your expectations.
            </p>
            <p class="about__text">
                Our shop specializes in full custom builds, performance upgrades, custom paint, and premium modifications 
                that make your bike truly unique.
            </p>
            <?php
        }
        ?>
    </div>
</section>

<!-- CUSTOMS GALLERY -->
<section class="gallery" id="customs">
    <div class="container">
        <div class="gallery__header">
            <h2 class="section-title">Our Custom Builds</h2>
        </div>
        
        <div class="gallery__grid" id="galleryGrid">
            <!-- Bike cards will be generated by JavaScript -->
        </div>
    </div>
</section>

<!-- CONTACT SECTION -->
<section class="contact" id="contact">
    <div class="container contact__container">
        <div class="contact__header">
            <h2 class="section-title">Get In Touch</h2>
            <p class="about__text">Ready to start your custom build? Contact us today.</p>
        </div>
        
        <?php echo do_shortcode('[badboybike_contact_form]'); ?>
    </div>
</section>

<?php
get_footer();


